version: "3"
services:
  api: 
    build: .
    depends_on:
      - postgres
    container_name: invoiceapi
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  postgres:
    image: postgres
    container_name: invoiceapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jes0sluv
      POSTGRES_DB: invoice_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: invoiceapi_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: invoiceapi_celery
    command: celery -A app.core.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - ./.env
        

volumes:
  postgres_data:
    driver: local
    