"""updated invoices table

Revision ID: 8718affe4d3a
Revises: d58056bbc05d
Create Date: 2025-06-21 23:02:44.781672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8718affe4d3a'
down_revision: Union[str, None] = 'd58056bbc05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('invoices_user_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_user_id_fkey'), 'invoices', 'users', ['user_id'], ['id'])
    op.drop_column('invoices', 'owner_id')
    # ### end Alembic commands ###
